#!/bin/sh
# memcal installer.
#
# Puts a `memcal` on your PATH that points at *this* source tree rather than a copy,
# so editing the code takes effect immediately with no reinstall. The current runtime has
# no third-party dependencies, so there is nothing to compile or resolve. If dependencies
# are added to pyproject.toml, this installer must install them before the launcher runs.
#
#   ./install.sh                 # ~/.local/bin/memcal, and `memcal init` if this is new
#   ./install.sh --nightly       # ...and schedule the dream pass for 3am
#   ./install.sh --bin DIR       # somewhere else on your PATH
#   ./install.sh --uninstall     # remove the launcher (never your data)
#
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
BIN="${HOME}/.local/bin"
DO_INIT=1
DO_NIGHTLY=0
UNINSTALL=0

while [ $# -gt 0 ]; do
    case "$1" in
        --bin)       BIN="${2:?--bin needs a directory}"; shift 2 ;;
        --bin=*)     BIN="${1#*=}"; shift ;;
        --no-init)   DO_INIT=0; shift ;;
        --nightly)   DO_NIGHTLY=1; shift ;;
        --uninstall) UNINSTALL=1; shift ;;
        -h|--help)   sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *)           echo "unknown option: $1  (try --help)" >&2; exit 2 ;;
    esac
done

say()  { printf '%s\n' "$*"; }
step() { printf '  %s\n' "$*"; }
warn() { printf '  ! %s\n' "$*" >&2; }

# ------------------------------------------------------------------ uninstall --

if [ "$UNINSTALL" -eq 1 ]; then
    say "removing memcal"
    # Unload the agent before the launcher goes, since launchctl is reached through it.
    if [ -f "$HOME/Library/LaunchAgents/com.memcal.nightly.plist" ]; then
        (cd "$ROOT" && python3 -m memcal schedule uninstall 2>/dev/null | sed 's/^/  /') \
            || warn "could not unload the nightly agent — launchctl bootout it by hand"
    fi
    removed=0
    for dir in "$BIN" "$HOME/.local/bin" /usr/local/bin; do
        target="$dir/memcal"
        if [ -f "$target" ] && grep -q "generated by memcal's install.sh" "$target" 2>/dev/null; then
            rm -f "$target" && step "removed $target" && removed=1
        fi
    done
    [ "$removed" -eq 1 ] || step "no launcher found"
    say ""
    say "your data is untouched: ${MEMCAL_HOME:-$HOME/.memcal}"
    say "the source tree is untouched: $ROOT"
    exit 0
fi

# --------------------------------------------------------------------- python --

py_ok() {
    [ -n "${1:-}" ] || return 1
    command -v "$1" >/dev/null 2>&1 || return 1
    "$1" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' 2>/dev/null
}

PY=""
for candidate in python3 python3.14 python3.13 python3.12 python3.11; do
    if py_ok "$candidate"; then PY=$(command -v "$candidate"); break; fi
done

if [ -z "$PY" ]; then
    say "memcal needs Python 3.11 or newer, and I could not find one."
    say ""
    say "  brew install python3          # or install from python.org"
    exit 1
fi

say "memcal"
step "source   $ROOT"
step "python   $PY ($("$PY" -c 'import sys; print(".".join(map(str, sys.version_info[:3])))'))"

if [ ! -d "$ROOT/memcal" ]; then
    warn "no memcal package at $ROOT/memcal — is install.sh still next to the source?"
    exit 1
fi

# ------------------------------------------------------------------- launcher --

mkdir -p "$BIN"
TARGET="$BIN/memcal"

cat > "$TARGET" <<EOF
#!/bin/sh
# memcal — generated by memcal's install.sh. Delete it or re-run that script freely.
#
# This points at the source tree instead of a copy of it, so edits to the code take
# effect on the next command with no reinstall.
MEMCAL_ROOT="$ROOT"
PY="$PY"

if [ ! -d "\$MEMCAL_ROOT/memcal" ]; then
    echo "memcal: no source tree at \$MEMCAL_ROOT — did it move? re-run its install.sh" >&2
    exit 1
fi

# The interpreter is pinned to whatever installed this, which is exact but survives only
# until the next upgrade renames it. Falling back keeps the command working.
if [ ! -x "\$PY" ]; then
    PY=\$(command -v python3) || { echo "memcal: no python3 on PATH" >&2; exit 1; }
fi

exec env PYTHONPATH="\$MEMCAL_ROOT\${PYTHONPATH:+:\$PYTHONPATH}" "\$PY" -m memcal "\$@"
EOF
chmod 755 "$TARGET"
step "launcher $TARGET"

# ----------------------------------------------------------------------- PATH --

case ":$PATH:" in
    *":$BIN:"*) ON_PATH=1 ;;
    *)          ON_PATH=0 ;;
esac

if [ "$ON_PATH" -eq 0 ]; then
    warn "$BIN is not on your PATH"
    case "${SHELL##*/}" in
        zsh)  rc="$HOME/.zshrc"  ;;
        bash) rc="$HOME/.bash_profile" ;;
        *)    rc="your shell's startup file" ;;
    esac
    say ""
    say "  echo 'export PATH=\"$BIN:\$PATH\"' >> $rc && exec \$SHELL"
    say ""
fi

# Something else called memcal that wins on PATH is worth knowing about now rather
# than after ten minutes of editing code that is not the code being run.
FOUND=$(command -v memcal 2>/dev/null || true)
if [ -n "$FOUND" ] && [ "$FOUND" != "$TARGET" ]; then
    warn "another memcal comes first on your PATH: $FOUND"
fi

# ----------------------------------------------------------------------- setup --

HOME_DIR="${MEMCAL_HOME:-$HOME/.memcal}"
FRESH=0
[ -f "$HOME_DIR/memcal.db" ] || FRESH=1

if [ "$DO_INIT" -eq 1 ]; then
    say ""
    if [ "$FRESH" -eq 1 ]; then
        say "first run — setting up $HOME_DIR"
    else
        say "already set up at $HOME_DIR — refreshing contacts and the brief"
    fi
    "$TARGET" init | sed 's/^/  /'
fi

if [ "$DO_NIGHTLY" -eq 1 ]; then
    say ""
    say "nightly"
    "$TARGET" schedule install | sed 's/^/  /'
fi

# ------------------------------------------------------------------- what next --

say ""
if [ ! -f "$ROOT/.env" ] && [ -z "${OPENROUTER_API_KEY:-}" ]; then
    warn "no OpenRouter key — the gate, the CLI and the brief all work without one,"
    warn "but the dream pass cannot run. Put a sk-or-... line in $ROOT/.env"
    say ""
fi

say "try:"
say "  memcal brief                 what your agent sees"
say "  memcal ingest all            pull the streams"
say "  memcal web                   what the gate did, in a browser"
say "  memcal dream --dry-run       price a pass before spending anything"
[ "$DO_NIGHTLY" -eq 1 ] || say "  memcal schedule install      run the dream pass every night"
say "  memcal doctor                check the whole setup"
