"""Manage the nightly launchd job."""

from __future__ import annotations

import json
import os
import plistlib
import subprocess
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path

from . import db
from .config import Config, PROJECT_ROOT

LABEL = "com.memcal.nightly"
ICAL_PERMISSION_LABEL = "com.memcal.ical-permission"
DEFAULT_HOUR = 3
DEFAULT_MINUTE = 0

#: Interval used to catch a missed run after wake.
WAKE_INTERVAL = 1800

#: Agents replaced by the combined nightly job.
RETIRED_LABELS = ("com.memcal.catchup", "com.memcal.missed")


def plist_path() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"


def retired_plist_paths() -> list[Path]:
    return [Path.home() / "Library" / "LaunchAgents" / f"{label}.plist"
            for label in RETIRED_LABELS]


#: An extensionless executable gives the background item a useful display name.
SCRIPT_NAMES = {"nightly": "memcal-nightly"}

#: Script names used by earlier schedule layouts.
LEGACY_SCRIPT_NAMES = {"nightly": ("nightly.sh",),
                       "retired": ("catchup.sh", "memcal-catchup", "memcal-missed")}


def script_path(cfg: Config) -> Path:
    return cfg.home / SCRIPT_NAMES["nightly"]


def stamp_path(cfg: Config) -> Path:
    """Path recording when the whole scheduled job last started."""
    return cfg.home / "nightly.last-start"


def log_path(cfg: Config) -> Path:
    return cfg.home / "nightly.log"


def _domain() -> str:
    return f"gui/{os.getuid()}"


def pinned_python(cfg: Config) -> str:
    """The interpreter the nightly script will actually execute."""
    script = script_path(cfg)
    if script.exists():
        for line in script.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("PY="):
                candidate = line[3:].strip().strip('"')
                if Path(candidate).is_file():
                    return candidate
                break
    return sys.executable


def calendar_permission_probe(cfg: Config, *, timeout: int = 45) -> tuple[bool, str]:
    """Request Calendar access from a temporary launchd agent.

    Running `osascript` from a terminal can authorize the terminal/Codex responsible
    process while the 03:00 job remains unapproved. This probe uses the same user
    launchd domain, source checkout, home, and pinned Python as the nightly agent.
    """
    cfg.ensure_dirs()
    python = pinned_python(cfg)
    plist = cfg.home / "ical-permission.plist"
    result = cfg.home / "ical-permission-result.json"
    try:
        result.unlink(missing_ok=True)
        with plist.open("wb") as fh:
            plistlib.dump({
                "Label": ICAL_PERMISSION_LABEL,
                "ProgramArguments": [
                    python, "-m", "memcal", "ical", "probe",
                    "--context", "nightly", "--result", str(result),
                ],
                "RunAtLoad": True,
                "ProcessType": "Interactive",
                "EnvironmentVariables": {
                    "MEMCAL_HOME": str(cfg.home),
                    "PYTHONPATH": str(PROJECT_ROOT),
                },
                "WorkingDirectory": str(PROJECT_ROOT),
            }, fh)
        _launchctl("bootout", f"{_domain()}/{ICAL_PERMISSION_LABEL}")
        code, message = _launchctl("bootstrap", _domain(), str(plist))
        if code:
            return False, f"could not start launchd Calendar probe: {message or code}"
        deadline = time.monotonic() + max(1, timeout)
        while time.monotonic() < deadline:
            if result.exists():
                try:
                    payload = json.loads(result.read_text(encoding="utf-8"))
                    ok = bool(payload.get("ok"))
                    detail = str(payload.get("message") or "no detail")
                    return ok, (
                        f"nightly launchd requester ({python}): {detail}"
                    )
                except (OSError, ValueError):
                    pass
            time.sleep(0.25)
        return False, (
            f"nightly launchd Calendar check timed out ({python}); "
            "a permission prompt may still be waiting"
        )
    finally:
        _launchctl("bootout", f"{_domain()}/{ICAL_PERMISSION_LABEL}")
        result.unlink(missing_ok=True)
        plist.unlink(missing_ok=True)


# ------------------------------------------------------------------ writing --

def render_script(cfg: Config, *, python: str | None = None) -> str:
    """Render the scheduled job."""
    python = python or sys.executable
    return f"""#!/bin/sh
# Generated by `memcal schedule install`; launchd executes this file directly.
# `memcal schedule run` executes the same file.
set -u

export MEMCAL_HOME="{cfg.home}"
PY="{python}"
LOG="{log_path(cfg)}"
STAMP="{stamp_path(cfg)}"

# Fall back when the interpreter recorded at installation has moved.
if [ ! -x "$PY" ]; then
    echo "note: $PY is gone — falling back to python3 on PATH" >&2
    PY="$(command -v python3)" || {{ echo "no python3 at all; giving up" >&2; exit 1; }}
fi

# Trim the log before opening it for this run.
if [ -f "$LOG" ] && [ "$(wc -c < "$LOG")" -gt 2000000 ]; then
    tail -n 1000 "$LOG" > "$LOG.trim" && mv "$LOG.trim" "$LOG"
fi
exec >> "$LOG" 2>&1

cd "{PROJECT_ROOT}" || exit 1

# `memcal schedule run` forces the owed path.
VERDICT="${{MEMCAL_RUN_NOW:-}}"
if [ "$VERDICT" != "owed" ]; then
    VERDICT="$("$PY" -m memcal schedule due 2>&1)"
fi

case "$VERDICT" in
    owed*) ;;
    ok*)
        # A catch-up fetch never invokes the model.
        OUT="$("$PY" -m memcal ingest --stale 2>&1)"
        STATUS=$?
        case "$OUT" in
            "nothing stale that is reachable right now") exit 0 ;;
        esac
        echo "=== $(date '+%Y-%m-%d %H:%M:%S')  catch-up ==="
        echo "$OUT"
        exit "$STATUS"
        ;;
    *)
        # Neither answer. `schedule status` reads launchd's last exit code, so a check
        # that cannot answer must exit non-zero rather than read as "nothing to do".
        echo "=== $(date '+%Y-%m-%d %H:%M:%S')  cannot tell whether a pass is owed ==="
        echo "$VERDICT"
        exit 1
        ;;
esac

# Record the start before ingest so later triggers do not duplicate this pass.
: > "$STAMP"

echo "=== $(date '+%Y-%m-%d %H:%M:%S')  nightly ==="

# Pull everything first: the dream pass reads the spool, so anything not ingested
# by now waits another day.
"$PY" -m memcal ingest all
INGEST=$?

# Frontier model, whole window. Nightly may overwrite what a cheaper pass wrote
# today; anything older than today is frozen unless new traffic references it.
"$PY" -m memcal dream --mode nightly
DREAM=$?

echo "=== $(date '+%Y-%m-%d %H:%M:%S')  done (ingest $INGEST, dream $DREAM) ==="

# Report dream failure first, otherwise the ingest result.
[ "$DREAM" -ne 0 ] && exit "$DREAM"
exit "$INGEST"
"""


def render_plist(cfg: Config, *, hour: int = DEFAULT_HOUR, minute: int = DEFAULT_MINUTE,
                 interval: int = WAKE_INTERVAL) -> dict:
    """Render the calendar, interval, and login triggers for one job."""
    return {
        "Label": LABEL,
        "ProgramArguments": [str(script_path(cfg))],
        "StartCalendarInterval": {"Hour": int(hour), "Minute": int(minute)},
        "StartInterval": int(interval),
        "RunAtLoad": True,
        # The script keeps its own log; this only catches a job that fails to start.
        "StandardOutPath": str(cfg.home / "launchd.err"),
        "StandardErrorPath": str(cfg.home / "launchd.err"),
        "ProcessType": "Background",
        "EnvironmentVariables": {"MEMCAL_HOME": str(cfg.home)},
        "WorkingDirectory": str(PROJECT_ROOT),
    }


def _launchctl(*args: str, runner=subprocess.run) -> tuple[int, str]:
    """One `launchctl` verb, as (exit code, what it said)."""
    try:
        proc = runner(["launchctl", *args], capture_output=True, text=True)
    except OSError as exc:
        return 127, f"launchctl is unavailable on this host: {exc}"
    return proc.returncode, (proc.stdout + proc.stderr).strip()


def install(cfg: Config, *, hour: int = DEFAULT_HOUR, minute: int = DEFAULT_MINUTE) -> list[str]:
    cfg.ensure_dirs()
    out = []

    script = script_path(cfg)
    previous = script.exists() and script.read_text(encoding="utf-8")
    script.write_text(render_script(cfg), encoding="utf-8")
    script.chmod(0o755)
    out.append(f"wrote {script}")
    out.extend(_retire_legacy(cfg, "nightly", render_script(cfg)))
    # Template comment changes are not user edits.
    if previous and _code_only(previous) != _code_only(render_script(cfg)):
        out.append(f"note: {script.name} had local edits and they were overwritten")

    # RunAtLoad must not turn installation into an immediate full pass.
    stamp = stamp_path(cfg)
    if not stamp.exists():
        stamp.touch()
        out.append(f"stamped {stamp.name} — the first pass is the next scheduled one")

    path = plist_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as fh:
        plistlib.dump(render_plist(cfg, hour=hour, minute=minute), fh)
    out.append(f"wrote {path}")

    # Replacing an existing agent means booting the old one out first; a bootstrap
    # over a loaded label fails with "service already loaded" and changes nothing.
    _launchctl("bootout", f"{_domain()}/{LABEL}")
    code, message = _launchctl("bootstrap", _domain(), str(path))
    if code != 0:
        # Older macOS, or a domain that will not take a bootstrap.
        code, message = _launchctl("load", "-w", str(path))
    if code != 0:
        out.append(f"launchctl refused it: {message or code}")
    else:
        out.append(f"loaded {LABEL} — next run {next_run(hour, minute)}, "
                   f"and on wake if that one is missed")
        out.extend(_retire_agents(cfg))
    out.append(f"log {log_path(cfg)}")
    return out


def _retire_agents(cfg: Config) -> list[str]:
    """Unload retired agents, then preserve their scripts."""
    out = []
    all_unloaded = True
    for label, path in zip(RETIRED_LABELS, retired_plist_paths()):
        loaded = _launchctl("print", f"{_domain()}/{label}")[0] == 0
        had_plist = path.exists()
        if loaded:
            code, message = _launchctl("bootout", f"{_domain()}/{label}")
            if code != 0:
                code, message = _launchctl("unload", "-w", str(path))
            if code != 0:
                all_unloaded = False
                out.append(f"could not retire {label}: {message or code}")
                continue
        if had_plist:
            path.unlink()
        if loaded or had_plist:
            out.append(f"retired {label} — one agent does its job now")
    if not all_unloaded:
        return out
    for name in LEGACY_SCRIPT_NAMES["retired"]:
        stale = cfg.home / name
        if stale.exists():
            kept = stale.with_name(stale.name + ".superseded")
            suffix = 1
            while kept.exists():
                kept = stale.with_name(f"{stale.name}.superseded.{suffix}")
                suffix += 1
            stale.rename(kept)
            out.append(f"retired {name} — kept as {kept.name}")
    return out


def _code_only(body: str) -> str:
    """Return executable script lines for local-edit detection."""
    return "\n".join(line.rstrip() for line in body.splitlines()
                      if line.strip() and not line.lstrip().startswith("#"))


def _retire_legacy(cfg: Config, which: str, current: str) -> list[str]:
    """Remove an unchanged legacy script and preserve an edited one."""
    out = []
    for name in LEGACY_SCRIPT_NAMES[which]:
        stale = cfg.home / name
        if not stale.exists():
            continue
        body = stale.read_text(encoding="utf-8", errors="replace")
        if _code_only(body) == _code_only(current):
            stale.unlink()
            out.append(f"removed {stale.name} — the job runs as {SCRIPT_NAMES[which]} now")
            continue
        kept = stale.with_name(stale.name + ".superseded")
        stale.rename(kept)
        out.append(f"{stale.name} had local edits — kept as {kept.name}; the job now runs "
                   f"{SCRIPT_NAMES[which]}, so move anything you want back")
    return out


def uninstall(cfg: Config) -> list[str]:
    out = []
    for label, path in [(LABEL, plist_path()), *zip(RETIRED_LABELS, retired_plist_paths())]:
        code, message = _launchctl("bootout", f"{_domain()}/{label}")
        if code != 0:
            _launchctl("unload", "-w", str(path))
        if code == 0:
            out.append(f"unloaded {label}")
        elif label not in RETIRED_LABELS:
            out.append(f"{label} not loaded ({message or 'already gone'})")
        if path.exists():
            path.unlink()
            out.append(f"removed {path}")
    out.append(f"left {script_path(cfg)} and the log in place")
    return out


def next_run(hour: int = DEFAULT_HOUR, minute: int = DEFAULT_MINUTE) -> str:
    now = datetime.now()
    when = now.replace(hour=int(hour), minute=int(minute), second=0, microsecond=0)
    if when <= now:
        when += timedelta(days=1)
    hours = (when - now).total_seconds() / 3600
    return f"{when:%a %H:%M} (in {hours:.1f}h)"


# ------------------------------------------------------------------ reading --

def scheduled_time(cfg: Config | None = None) -> tuple[int, int]:
    """The hour and minute the installed agent holds. `--hour` is a real option, so
    03:00 is a default, not a fact."""
    try:
        with plist_path().open("rb") as fh:
            interval = plistlib.load(fh).get("StartCalendarInterval", {})
        if isinstance(interval, list):
            interval = interval[0] if interval else {}
        return (int(interval.get("Hour", DEFAULT_HOUR)),
                int(interval.get("Minute", DEFAULT_MINUTE)))
    except Exception:
        return DEFAULT_HOUR, DEFAULT_MINUTE


def last_due(now: datetime, hour: int, minute: int) -> datetime:
    """The most recent moment the pass was supposed to start."""
    due = now.replace(hour=int(hour), minute=int(minute), second=0, microsecond=0)
    return due - timedelta(days=1) if due > now else due


def last_started(cfg: Config) -> datetime | None:
    """When the job last began, or None if it never has on this store."""
    try:
        return datetime.fromtimestamp(stamp_path(cfg).stat().st_mtime).astimezone()
    except OSError:
        return None


def owed(cfg: Config, *, now: datetime | None = None) -> tuple[datetime | None, str]:
    """`(the due time that went unserved, why)`; the first is None when none did.

    The window is one night wide: a machine off for a week runs one pass when it comes
    back, not seven, and a pass at 08:00 does not leave tonight's 03:00 looking served.
    """
    now = now or db.now_dt()
    if not plist_path().exists():
        return None, "the job is not installed, so nothing is due"
    script = script_path(cfg)
    if not script.exists():
        return None, (f"{script} does not exist, so there is nothing to run — "
                      f"`memcal schedule install` regenerates it")
    hour, minute = scheduled_time(cfg)
    due = last_due(now, hour, minute)
    started = last_started(cfg)
    if started is None:
        # Only reachable if the stamp was deleted, since `install` writes one. Owed is
        # the safer wrong answer: one extra pass beats never running.
        return due, "never — no pass has been recorded on this store"
    if started >= due:
        # Worded about the job, not about 03:00: `install` stamps a fresh store at
        # whatever time it runs, and "the 03:00 pass ran at 12:59" would be a lie.
        return None, f"{started:%a %d %b %H:%M} — nothing missed"
    return due, (f"{started:%a %d %b %H:%M} — the {due:%a %H:%M} pass is owed and "
                 f"runs at the next wake-up")


def status(cfg: Config, *, runner=subprocess.run) -> dict:
    installed = plist_path().exists()
    scheduled = None
    if installed:
        try:
            with plist_path().open("rb") as fh:
                data = plistlib.load(fh)
            interval = data.get("StartCalendarInterval", {})
            scheduled = (int(interval.get("Hour", 0)), int(interval.get("Minute", 0)))
        except Exception:
            scheduled = None

    code, listing = _launchctl("print", f"{_domain()}/{LABEL}", runner=runner)
    loaded = code == 0
    last_exit = None
    for line in listing.splitlines():
        if "last exit code" in line:
            last_exit = line.split("=")[-1].strip()

    log = log_path(cfg)
    tail = ""
    if log.exists():
        lines = log.read_text(encoding="utf-8", errors="replace").splitlines()
        tail = "\n".join(lines[-12:])

    # A job that runs nightly and fails nightly looks exactly like a quiet week from
    # every other angle, so the things most likely to rot get checked by name.
    warning = None
    script = script_path(cfg)
    if installed and not script.exists():
        # The failure this check exists for, and the one it originally missed: the plist
        # was loaded and pointed at a script that was not there, launchd wrote
        # `nightly.sh: No such file or directory` into launchd.err every night, and
        # nothing read that file. The store went five days with one dream run in its
        # entire life while `memcal schedule` reported the job installed and loaded.
        #
        # The old check only looked *inside* the script, so a missing script skipped it
        # entirely — the one thing that actually broke was the one thing not checked.
        warning = (f"{script} does not exist, so the job fails every night the moment "
                   f"launchd starts it — run `memcal schedule install` to regenerate it")
    elif script.exists():
        for line in script.read_text(encoding="utf-8").splitlines():
            if line.startswith("PY="):
                pinned = line[3:].strip().strip('"')
                if not Path(pinned).exists():
                    warning = (f"the pinned interpreter {pinned} is gone — the job falls "
                               f"back to python3 on PATH; reinstall to re-pin")
                break

    # launchd's own stderr, which is where a job that cannot start says so. Nothing read
    # it before, which is why the missing script was invisible for five days.
    err = cfg.home / "launchd.err"
    startup_error = ""
    if err.exists():
        startup_error = err.read_text(encoding="utf-8", errors="replace").strip()[-400:]
        if startup_error and not warning:
            warning = f"launchd could not start the job: {startup_error.splitlines()[-1]}"

    # launchd has been reporting `last exit code = 127` — the shell's "command not
    # found" — every night, and it was parsed out of the listing above and then only
    # ever printed. A nightly job that exits non-zero is failing, whatever the cause,
    # and that is worth saying in the same breath as "installed: yes".
    #
    # But launchd spells "has not run yet" as `last exit code = (never exited)`, in the
    # same field, so a freshly installed job read as a failing one the moment the
    # missing-script warning above stopped taking priority. That is the sentinel shape
    # exactly: the one value meaning *no value* satisfied a test for a bad value. Only
    # an integer is an exit code; anything else is launchd saying it has nothing yet.
    try:
        exited_with = int(str(last_exit).strip())
    except (TypeError, ValueError):
        exited_with = 0
    if not warning and exited_with != 0:
        warning = (f"the last run exited {last_exit} — the job is installed but not "
                   f"working; see {log_path(cfg)}")

    # Reported, not warned about: an owed pass is picked up by the next wake-up.
    due, why = owed(cfg)
    started = last_started(cfg)
    return {
        "warning": warning,
        "installed": installed,
        "loaded": loaded,
        "label": LABEL,
        "plist": str(plist_path()),
        "script": str(script_path(cfg)),
        "log": str(log) if log.exists() else None,
        "at": scheduled,
        "every": WAKE_INTERVAL,
        "next": next_run(*scheduled) if scheduled else None,
        "last_start": started.isoformat(timespec="seconds") if started else None,
        "owed": due.isoformat(timespec="seconds") if due else None,
        "why": why,
        "last_exit": last_exit,
        "startup_error": startup_error,
        "tail": tail,
    }


def run_now(cfg: Config, *, force: bool = True) -> int:
    """Run the script itself, not a reimplementation of it. If the two could drift,
    a green result here would say nothing about what happens at 03:00.

    `force` overrides the script's own owed check; typing `memcal schedule run` has
    already answered that question.
    """
    script = script_path(cfg)
    if not script.exists():
        print("not installed — run `memcal schedule install` first")
        return 1
    print(f"running {script} (output goes to {log_path(cfg)})")
    env = dict(os.environ)
    if force:
        env["MEMCAL_RUN_NOW"] = "owed"
    # Exactly what launchd runs — the file itself, through its shebang. Invoking
    # `/bin/sh <script>` here would still work and would stop this being a test of the
    # thing that actually happens at 03:00, which is the whole point of the function.
    return subprocess.run([str(script)], env=env).returncode
