"""Compatibility facade for the local web surface."""

import socket
from pathlib import Path

from .config import Config
from .web_dream import (
    _budget_history,
    _bundle_card,
    _bundle_id,
    _cost_estimate,
    _request_card,
    dream_preview,
)
from .web_jobs import (
    _Job,
    _PHASES,
    _blank_step,
    _phase_from,
    _read_so_far,
    _reporter,
    _trim_completed_jobs,
    collect_work,
    dream_work,
    find_job,
    job_status,
    start_job,
)
from .web_memory import (
    FACETS,
    _FACET_INDEX,
    _FACET_LOCK,
    _TABLE,
    _TITLE_STOP_WORDS,
    _contract,
    _event_detail,
    _event_summary,
    _excerpts,
    _facet_index,
    _facet_key,
    _facet_watermark,
    _needle,
    _pretty_json,
    _related_events,
    _title_terms,
    _wiki_link,
    event_list,
    memory,
    overview,
    run_detail,
    runs,
    trace_call,
    why,
    wiki_pages,
)
from .web_queue import (
    ARCHIVE_JOIN,
    GROUP_KEY,
    ITEM_SELECT,
    PREVIEW_CHARS,
    QUEUE_CLAUSES,
    _filters,
    _item,
    _meta,
    _queue_sender,
    _queue_state,
    _who,
    block,
    conversations,
    counterparts,
    groups,
    item_detail,
    items,
    queue_item,
    senders,
    set_sender,
)
from .web_server import (
    CSRF_COOKIE,
    MAX_REQUEST_BYTES,
    PAGE,
    STATIC_DIR,
    STATIC_TYPES,
    Handler,
    IPv6ThreadingHTTPServer,
    RequestBodyError,
    WebError,
    _csrf_cookie,
    _has_expected_host,
    _is_loopback_host,
    _is_same_origin_mutation,
    _origin_for,
    _read_json_body,
    _who_has,
    frontend_source,
    serve,
)
